### ISSUE TITLE
Add GH actions to build our own flatpak remote

### ISSUE THREAD

**Issue by ojoeth** [surfaceflinger/com.lunarclient.Launcher#4]
As mentioned by #1 it would be nice to provide an easy way to install this flatpak.
There is a template by the maintainer of multiple widely used flatpaks which can use GitHub Actions to automatically build a flatpak and create a remote for people to add and download from.
https://github.com/TheEvilSkeleton/flatpak-remote

**Comment by DaPigGuy** [comment]
Is there a reason not to attempt publishing to Flathub? Flathub does not require any involvement from the app developer, and most users are likely to have that remote already added.

**Comment by surfaceflinger** [comment]
https://github.com/flathub/com.lunarclient.LunarClient
